variables:
- name: isMain
  value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
- name: isDev
  value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}
- name: isPr
  value: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
- name: isScheduled
  value: ${{ eq(variables['Build.Reason'], 'Schedule') }}
- name: isManual
  value: ${{ eq(variables['Build.Reason'], 'Manual') }}

- name: isTag
  value: ${{ startsWith(variables['build.sourceBranch'], 'refs/tags/') }}

- name: compareBranch
  ${{ if eq(variables.isMain, 'true') }}:
    value: HEAD~
  ${{ elseif eq(variables.isPr, 'true') }}:
    value: $(System.PullRequest.TargetBranch)
  ${{ elseif eq(variables.isDev, 'true') }}:
    value: main
  ${{ else }}:
    value: dev